# main.py - Nova Hub with modular API structure
#
# Architecture:
# - Service API at /service/* (OAuth2 for nova_client)
# - Management API at /management/* (Session JWT for admin UI)
# - Vue.js SPA served from frontend/dist

import sys
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from backend.api.management import management_router
from backend.api.service import service_router
from backend.core.version import __version__
from backend.core.config import get_config, init_config
from backend.core.database import get_db, get_session, init_database
from backend.core.middleware import AuthContextMiddleware
from backend.logging_config import get_logger, init_logging_from_config

# Initialize config on module load
config = init_config()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup and shutdown events"""
    # Initialize logging FIRST before any other operations
    init_logging_from_config(config._raw)
    logger = get_logger(context="startup")

    # Validate JWT secret strength before doing anything else
    from backend.core.security import validate_jwt_secret
    try:
        validate_jwt_secret(config.security.jwt_secret)
    except ValueError as e:
        logger.error(f"STARTUP ABORTED: {e}")
        sys.exit(1)

    # Initialize database
    db_path = config.database.path
    database_url = f"sqlite:///{db_path}"
    database = init_database(database_url)
    app.state.database = database
    app.state.config = config

    # Note: Run migrations manually with: alembic upgrade head
    # Automatic migrations disabled to prevent startup hangs

    # Start packet watcher for hub-generated outbound packets
    from backend.services.packet_service import PacketService
    from backend.services.packet_watcher import WatcherService
    import asyncio

    db_session = get_session()
    watcher = None
    try:
        # Get the current event loop
        loop = asyncio.get_running_loop()

        packet_service = PacketService(db_session)
        watcher = WatcherService(packet_service, config._raw, loop)
        watcher.start()
        app.state.watcher = watcher

        # Process any existing files in watched directories
        # (files that were there before the watcher started)
        await watcher.process_pending_scans()

    except Exception as e:
        logger.exception(f"Failed to start packet watcher: {e}")
    finally:
        db_session.close()

    # Honour [processing] retention_days. Runs once at startup and daily after,
    # so a hub that is restarted often still prunes exactly once per day's worth
    # of uptime rather than on every boot. See retention_service.py for why this
    # blanks bulk columns instead of deleting rows.
    app.state.retention_task = asyncio.create_task(_retention_loop(config))

    logger.info("Nova Hub started successfully")

    yield

    # Shutdown
    if hasattr(app.state, "watcher") and app.state.watcher:
        app.state.watcher.stop()

    task = getattr(app.state, "retention_task", None)
    if task is not None:
        task.cancel()

    logger.info("Nova Hub shutting down...")


async def _retention_loop(config):
    """Daily retention pass.

    Deliberately a plain loop rather than a scheduler dependency: it has one
    job, and a purge that fails must not be able to take the hub down with it.
    """
    import asyncio

    from backend.services.retention_service import from_config

    logger = get_logger(context="retention")
    while True:
        session = get_session()
        try:
            service = from_config(session, config)
            if not service.enabled:
                logger.debug("retention disabled; loop idle")
            else:
                await asyncio.to_thread(service.purge)
        except asyncio.CancelledError:
            raise
        except Exception as e:
            logger.exception(f"Retention pass failed (the hub is unaffected): {e}")
        finally:
            session.close()
        await asyncio.sleep(24 * 60 * 60)


# --- Service API Sub-Application ---
service_app = FastAPI(
    title="Nova Hub - Service API",
    description="""
# Service API for nova_client

This API is used by BBS clients running nova_client to:

- **Authenticate** using OAuth2 client credentials flow
- **Upload packets** generated by BRE/FE door games
- **Download packets** destined for their BBS (poll `/leagues/{league_id}/packets?unread=true`)
- **Download nodelists** for league member information

## Authentication

All endpoints except `/auth/token` require OAuth2 Bearer token authentication.

1. Request token: `POST /api/v1/auth/token` with `client_id` and `client_secret`
2. Use token: `Authorization: Bearer <token>` header

## Packet Naming Convention

Packets follow the format: `<league><game><source><dest>.<seq>`

- **league**: 3-digit league number (e.g., 555)
- **game**: B (BRE) or F (FE)
- **source**: 2-digit hex BBS index (01-FF)
- **dest**: 2-digit hex BBS index (01-FF)
- **seq**: 3-digit sequence number (000-999, wraps)

Example: `555B0201.001` = BRE League 555, from BBS 02 to BBS 01, sequence 1
    """,
    version=__version__,
    docs_url="/docs",
    redoc_url="/redoc",
    license_info={"name": "MIT"},
)

service_app.add_middleware(AuthContextMiddleware)
service_app.include_router(service_router, prefix="/api/v1")


# --- Management API Sub-Application ---
management_app = FastAPI(
    title="Nova Hub - Management API",
    description="""
# Management API for Sysop Administration

This API powers the Nova Hub admin dashboard and provides:

- **Session Authentication** using JWT cookies
- **Dashboard** statistics and activity feed (polled via REST)
- **Client Management** - CRUD operations for BBS clients
- **League Management** - Leagues and membership configuration
- **Processing Runs** - View processing history and logs
- **Alerts** - Sequence gap detection and resolution
- **User Management** - Admin user CRUD (admin only)

## Authentication

Uses session-based JWT stored in httpOnly cookies.

1. Login: `POST /api/v1/auth/login` with username/password
2. Cookie automatically included in subsequent requests
3. Logout: `POST /api/v1/auth/logout`
    """,
    version=__version__,
    docs_url="/docs",
    redoc_url="/redoc",
    license_info={"name": "MIT"},
)

# CORS for Vue.js dev server (development only)
if config.server.environment == "development":
    management_app.add_middleware(
        CORSMiddleware,
        allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

management_app.add_middleware(AuthContextMiddleware)
management_app.include_router(management_router, prefix="/api/v1")


# --- Main Application ---
app = FastAPI(
    title="Nova Hub",
    description="""
# Nova Hub - BBS Inter-League Routing System

Modern routing hub for Solar Realms games: Barren Realms Elite (BRE) and Falcon's Eye (FE).

## API Documentation

- **Service API**: [/service/docs](/service/docs) - For nova_client (OAuth2)
- **Management API**: [/management/docs](/management/docs) - For admin UI (Session JWT)

## Features

- **Packet Routing**: Hub-and-spoke routing for BBS door game leagues
- **OAuth Authentication**: Secure client authentication for packet transfer
- **Dashboard Polling**: REST-based dashboard updates (no WebSocket)
- **Sequence Validation**: Automatic detection of missing packets
- **Web Interface**: Comprehensive sysop dashboard
    """,
    version=__version__,
    docs_url=None,
    redoc_url=None,
    lifespan=lifespan,
)

# Mount sub-applications
app.mount("/service", service_app)
app.mount("/management", management_app)

# --- Vue.js Frontend Serving ---
FRONTEND_DIST = Path(__file__).parent / "frontend" / "dist"

# Mount static assets from Vue.js build (JS, CSS, images)
if FRONTEND_DIST.exists():
    app.mount("/assets", StaticFiles(directory=FRONTEND_DIST / "assets"), name="assets")


# Health check endpoint
@app.get("/health", tags=["System"])
async def health_check():
    """
    Health check endpoint for monitoring

    Returns system status and database connectivity
    """
    from sqlalchemy import text

    db = get_session()
    try:
        # Test database connection
        db.execute(text("SELECT 1"))
        db_status = "healthy"
    except Exception as e:
        db_status = f"unhealthy: {str(e)}"
    finally:
        db.close()

    return {
        "status": "healthy" if db_status == "healthy" else "degraded",
        "database": db_status,
        "version": app.version,
        "apis": {
            "service": "/service/docs",
            "management": "/management/docs",
        },
    }


# API overview endpoint
@app.get("/api", tags=["System"])
async def api_overview():
    """
    API overview showing available endpoints
    """
    return {
        "nova_hub": {
            "version": app.version,
            "documentation": {
                "service_api": "/service/docs",
                "management_api": "/management/docs",
            },
            "endpoints": {
                "service": {
                    "base_url": "/service/api/v1",
                    "authentication": "OAuth2 client credentials",
                    "purpose": "BBS client packet routing",
                },
                "management": {
                    "base_url": "/management/api/v1",
                    "authentication": "Session JWT (cookie)",
                    "purpose": "Sysop administration dashboard",
                },
            },
        }
    }


# --- SPA Catch-All Route (MUST be last) ---
@app.get("/{full_path:path}", include_in_schema=False)
async def serve_spa(request: Request, full_path: str):
    """
    Serve Vue.js SPA for all non-API routes.
    This enables Vue Router to handle client-side routing.
    Must be defined LAST to allow other routes to match first.
    """
    # Check if frontend build exists
    index_path = FRONTEND_DIST / "index.html"
    if not index_path.exists():
        # Development mode - return helpful message
        return {
            "message": "Frontend not built",
            "hint": "Run 'cd frontend && pnpm run build' to build the Vue.js frontend",
            "apis": {
                "service": "/service/docs",
                "management": "/management/docs",
            },
        }

    return FileResponse(index_path)
