"""initial_schema

Revision ID: 5e5855c5acbb
Revises: 
Create Date: 2026-01-09 04:27:48.222915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5855c5acbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret', sa.String(length=128), nullable=False),
    sa.Column('bbs_name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.String(length=10), nullable=False),
    sa.Column('game_type', sa.String(length=1), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('dosemu_path', sa.String(length=255), nullable=True),
    sa.Column('game_executable', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_index(op.f('ix_leagues_league_id'), 'leagues', ['league_id'], unique=False)
    op.create_table('sysop_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_sysop_users_id'), 'sysop_users', ['id'], unique=False)
    op.create_index(op.f('ix_sysop_users_username'), 'sysop_users', ['username'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('league_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('bbs_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_memberships_bbs_index'), 'league_memberships', ['bbs_index'], unique=False)
    op.create_index(op.f('ix_league_memberships_id'), 'league_memberships', ['id'], unique=False)
    op.create_table('processing_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('packets_processed', sa.Integer(), nullable=True),
    sa.Column('packets_failed', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('stdout_log', sa.Text(), nullable=True),
    sa.Column('stderr_log', sa.Text(), nullable=True),
    sa.Column('dosemu_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_runs_id'), 'processing_runs', ['id'], unique=False)
    op.create_index(op.f('ix_processing_runs_started_at'), 'processing_runs', ['started_at'], unique=False)
    op.create_table('sequence_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('source_bbs_index', sa.String(length=2), nullable=False),
    sa.Column('dest_bbs_index', sa.String(length=2), nullable=False),
    sa.Column('expected_sequence', sa.Integer(), nullable=False),
    sa.Column('received_sequence', sa.Integer(), nullable=False),
    sa.Column('gap_size', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_alerts_detected_at'), 'sequence_alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_sequence_alerts_id'), 'sequence_alerts', ['id'], unique=False)
    op.create_table('packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('source_bbs_index', sa.String(length=2), nullable=False),
    sa.Column('dest_bbs_index', sa.String(length=2), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('source_client_id', sa.Integer(), nullable=True),
    sa.Column('dest_client_id', sa.Integer(), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_run_id', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('is_downloaded', sa.Boolean(), nullable=True),
    sa.Column('has_error', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dest_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], ),
    sa.ForeignKeyConstraint(['source_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packets_filename'), 'packets', ['filename'], unique=False)
    op.create_index(op.f('ix_packets_id'), 'packets', ['id'], unique=False)
    op.create_index(op.f('ix_packets_uploaded_at'), 'packets', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packets_uploaded_at'), table_name='packets')
    op.drop_index(op.f('ix_packets_id'), table_name='packets')
    op.drop_index(op.f('ix_packets_filename'), table_name='packets')
    op.drop_table('packets')
    op.drop_index(op.f('ix_sequence_alerts_id'), table_name='sequence_alerts')
    op.drop_index(op.f('ix_sequence_alerts_detected_at'), table_name='sequence_alerts')
    op.drop_table('sequence_alerts')
    op.drop_index(op.f('ix_processing_runs_started_at'), table_name='processing_runs')
    op.drop_index(op.f('ix_processing_runs_id'), table_name='processing_runs')
    op.drop_table('processing_runs')
    op.drop_index(op.f('ix_league_memberships_id'), table_name='league_memberships')
    op.drop_index(op.f('ix_league_memberships_bbs_index'), table_name='league_memberships')
    op.drop_table('league_memberships')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_sysop_users_username'), table_name='sysop_users')
    op.drop_index(op.f('ix_sysop_users_id'), table_name='sysop_users')
    op.drop_table('sysop_users')
    op.drop_index(op.f('ix_leagues_league_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
