"""add_fidonet_address_to_league_membership

Revision ID: b2dad0bf570b
Revises: 5e5855c5acbb
Create Date: 2026-01-09 08:23:17.934405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dad0bf570b'
down_revision = '5e5855c5acbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_memberships', sa.Column('fidonet_address', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_league_memberships_fidonet_address'), 'league_memberships', ['fidonet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_league_memberships_fidonet_address'), table_name='league_memberships')
    op.drop_column('league_memberships', 'fidonet_address')
    # ### end Alembic commands ###
