"""Service API league operations (nodelist download)"""

from datetime import datetime
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Path as PathParam, Request
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from backend.core.database import get_db
from backend.core.security import get_current_client
from backend.logging_config import get_logger
from backend.models.database import Client, League, LeagueMembership, Packet
from backend.services.league_utils import parse_league_id
from backend.services.processing_service import find_file_case_insensitive

logger = get_logger(context="service_leagues")

router = APIRouter()


@router.get("/{league_id}/nodelist", summary="Download Nodelist")
async def download_nodelist(
    league_id: str = PathParam(..., pattern=r'^\d{3}[BF]$'),
    request: Request = None,
    client: Client = Depends(get_current_client),
    db: Session = Depends(get_db),
):
    """
    Download the latest nodelist file for a league

    **Path Parameters:**
    - `league_id`: League identifier with game type (e.g., "555B" for BRE, "555F" for FE)

    **Returns:** Binary nodelist file (BRNODES.xxx or FENODES.xxx)

    **Description:**
    The nodelist contains information about all BBS nodes in the league.
    These files are generated by the hub and should be placed in your game directory.

    **Authentication:** Requires Bearer token and league membership

    **Example:**
    ```bash
    curl -X GET "https://hub.example.com/service/api/v1/leagues/555B/nodelist" \\
      -H "Authorization: Bearer YOUR_TOKEN" \\
      -o BRNODES.555
    ```
    """
    # Parse league_id from URL
    league_number, league_game_type = parse_league_id(league_id)

    # Get league
    league = (
        db.query(League)
        .filter(
            League.league_id == league_number,
            League.game_type == league_game_type
        )
        .first()
    )

    if not league:
        raise HTTPException(status_code=404, detail=f"League {league_id} not found")

    # Check if client is a member
    membership = (
        db.query(LeagueMembership)
        .filter(
            LeagueMembership.client_id == client.id,
            LeagueMembership.league_id == league.id,
            LeagueMembership.is_active == True,
        )
        .first()
    )

    if not membership:
        raise HTTPException(
            status_code=403,
            detail=f"Client {client.client_id} is not a member of league {league_id}",
        )

    # Determine game type
    game_type = "BRE" if league.game_type == "B" else "FE"

    # Construct nodelist filename
    nodelist_filename = f"{'BR' if game_type == 'BRE' else 'FE'}NODES.{league_number}"

    # Find nodelist file
    data_dir = request.app.state.config.get("server", {}).get("data_dir", "./data")
    nodelists_dir = Path(data_dir) / "nodelists" / game_type.lower() / league_number

    nodelist_path = find_file_case_insensitive(nodelists_dir, nodelist_filename)

    if not nodelist_path or not nodelist_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Nodelist not available for league {league_id}",
        )

    logger.info(f"Client {client.client_id} downloading nodelist: {nodelist_path.name}")

    # Mark the nodelist packet as downloaded
    dest_bbs_hex = f"{membership.bbs_index:02X}"
    nodelist_packet = (
        db.query(Packet)
        .filter(
            Packet.filename == nodelist_path.name,
            Packet.league_id == league.id,
            Packet.dest_bbs_index == dest_bbs_hex,
        )
        .first()
    )

    if nodelist_packet:
        nodelist_packet.downloaded_at = datetime.now()
        nodelist_packet.is_downloaded = True
        db.commit()
        logger.debug(f"Marked nodelist packet {nodelist_path.name} as downloaded for BBS {dest_bbs_hex}")

    return FileResponse(
        nodelist_path,
        filename=nodelist_path.name,
        media_type="application/octet-stream",
    )
